---
title: "EC4308"
author: "Brandon Neo Bing Jie"
date: "2025-04-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries

```{r}
library(dplyr)
library(stringr)

```

# Importing data

```{r}

df <- read.csv("../data/updated_hdb_data.csv")
df <- df %>%
  mutate(
    level = str_extract_all(storey_range, "\\d{2}") %>% 
             lapply(function(x) mean(as.numeric(x))) %>% 
             unlist()
  ) 

df
```

```{r}
cols_to_drop <- c("X", "Unnamed..0.1", "Unnamed..0", "row", "date", "town", "flat_type", "block", "street_name", "storey_range", "flat_model", "lease_commence_date",
                  "year", "month_num", "address", "latitude", "longitude", "mrt_stations_within_1km", "nearest_mrt_station", "pri_schs_within_1km", "hawkers_within_1km",
                  "nearest_hawker", "month_Dec", "flat_type_1.ROOM", "flat_model_Multi.Generation", "town_ANG.MO.KIO", "remaining_lease")


df_cleaned = df[ , !(names(df) %in% cols_to_drop)]
df_cleaned

write.csv(df_cleaned, "../data/processed_hdb_data.csv", row.names = FALSE)
```